# 🧠 Mental Health Intelligence Platform

## Phase 2 : Data Cleaning

### Project Overview

Real-world datasets are rarely clean.

Before performing exploratory analysis or building predictive models, the dataset must be assessed for quality issues and cleaned systematically.

This notebook focuses exclusively on improving the quality of the unified OSMI Mental Health Survey dataset.

---

### Objectives

- Remove duplicate records

- Handle missing values

- Standardize categorical variables

- Clean inconsistent text

- Validate numerical variables

- Prepare a trustworthy dataset for analysis

> No feature engineering or machine learning is performed in this notebook.

## Import Required Libraries

The following libraries are required for cleaning and preprocessing the dataset.

In [3]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries Imported Successfully")

Libraries Imported Successfully

## Load Unified Dataset

Load the unified survey dataset generated during the data integration stage.

In [4]:
df = pd.read_csv("../data/processed/unified_osmi_data.csv", low_memory=False)

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

df.head()

Rows    : 3095
Columns : 85

,source_file,survey_year,self_employed,no_employees,tech_company,primary_role_tech,benefits,know_options,formal_discussion,resources,anonymity,leave_ease,comfort_physical_mental,comfort_supervisor,discussed_with_employer,comfort_coworkers,discussed_with_coworkers,coworker_discussed_with_you,employer_importance_physical,employer_importance_mental,coverage_mental_health,know_resources,reveal_to_clients,reveal_to_coworkers,productivity_affected,productivity_percent_affected,have_prev_employers,prev_tech_company,prev_benefits,prev_know_options,prev_formal_discussion,prev_resources,prev_anonymity,prev_comfort_physical_mental,prev_comfort_supervisor,prev_discussed_with_employer,prev_comfort_coworkers,prev_discussed_with_coworkers,prev_employer_importance_physical,prev_employer_importance_mental,currently_disordered,diagnosed_disorder,disorder_anxiety,disorder_mood,disorder_psychotic,disorder_eating,disorder_adh_add,disorder_personality,disorder_ocd,disorder_ptsd,disorder_stress_response,disorder_dissociative,disorder_substance_use,disorder_addictive,disorder_other,past_disorder,sought_treatment,family_history,interference_when_treated,interference_when_not_treated,observations_less_likely_reveal,share_with_friends_family,bring_up_physical_interview,bring_up_physical_why,bring_up_mental_interview,bring_up_mental_why,openly_identified,identified_affected_career,identified_affected_how,team_reaction_if_knew,observed_unsupportive_response,unsupportive_response_desc,observed_supportive_response,supportive_response_desc,industry_support_rating,improvement_suggestions,additional_comments,willing_to_interview,age,gender,country_live,state_live,race,country_work,state_work
0,2014,2014,NaN,6-25,Yes,NaN,Yes,Not sure,No,Yes,Yes,Somewhat easy,Yes,Yes,No,Some of them,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,No,Often,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2014,2014,NaN,More than 1000,No,NaN,Don't know,No,Don't know,Don't know,Don't know,Don't know,Don't know,No,Maybe,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,Rarely,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014,2014,NaN,6-25,Yes,NaN,No,No,No,No,Don't know,Somewhat difficult,No,Yes,No,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,Rarely,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2014,2014,NaN,26-100,Yes,NaN,No,Yes,No,No,No,Somewhat difficult,No,No,Yes,Some of them,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,Often,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2014,2014,NaN,100-500,Yes,NaN,Yes,No,Don't know,Don't know,Don't know,Don't know,Don't know,Yes,No,Some of them,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,Never,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Dataset Overview

Before making any modifications, we inspect the structure of the dataset.

The inspection includes:

- dataset dimensions
- data types
- missing values
- duplicate rows
- unique values

This establishes the baseline quality of the raw dataset.

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 85 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   source_file                        3095 non-null   int64
 1   survey_year                        3095 non-null   int64
 2   self_employed                      1241 non-null   str
 3   no_employees                       2836 non-null   str
 4   tech_company                       2836 non-null   str
 5   primary_role_tech                  1577 non-null   str
 6   benefits                           2193 non-null   str
 7   know_options                       2673 non-null   str
 8   formal_discussion                  2836 non-null   str
 9   resources                          2836 non-null   str
 10  anonymity                          2836 non-null   str
 11  leave_ease                         2836 non-null   str
 12  comfort_physical_mental            2836 non-null   str
 13  comfort_supervisor                 2836 non-null   str
 14  discussed_with_employer            2836 non-null   str
 15  comfort_coworkers                  2836 non-null   str
 16  discussed_with_coworkers           1572 non-null   str
 17  coworker_discussed_with_you        1569 non-null   str
 18  employer_importance_physical       1577 non-null   float64
 19  employer_importance_mental         1577 non-null   float64
 20  coverage_mental_health             259 non-null    str
 21  know_resources                     259 non-null    str
 22  reveal_to_clients                  259 non-null    str
 23  reveal_to_coworkers                259 non-null    str
 24  productivity_affected              259 non-null    str
 25  productivity_percent_affected      194 non-null    str
 26  have_prev_employers                1173 non-null   float64
 27  prev_tech_company                  1546 non-null   str
 28  prev_benefits                      1546 non-null   str
 29  prev_know_options                  1546 non-null   str
 30  prev_formal_discussion             1546 non-null   str
 31  prev_resources                     1546 non-null   str
 32  prev_anonymity                     1546 non-null   str
 33  prev_comfort_physical_mental       1546 non-null   str
 34  prev_comfort_supervisor            1546 non-null   str
 35  prev_discussed_with_employer       1546 non-null   str
 36  prev_comfort_coworkers             1546 non-null   str
 37  prev_discussed_with_coworkers      1538 non-null   str
 38  prev_employer_importance_physical  1546 non-null   float64
 39  prev_employer_importance_mental    1546 non-null   float64
 40  currently_disordered               1173 non-null   str
 41  diagnosed_disorder                 515 non-null    str
 42  disorder_anxiety                   0 non-null      float64
 43  disorder_mood                      0 non-null      float64
 44  disorder_psychotic                 0 non-null      float64
 45  disorder_eating                    0 non-null      float64
 46  disorder_adh_add                   0 non-null      float64
 47  disorder_personality               0 non-null      float64
 48  disorder_ocd                       0 non-null      float64
 49  disorder_ptsd                      0 non-null      float64
 50  disorder_stress_response           0 non-null      float64
 51  disorder_dissociative              0 non-null      float64
 52  disorder_substance_use             0 non-null      float64
 53  disorder_addictive                 0 non-null      float64
 54  disorder_other                     0 non-null      float64
 55  past_disorder                      1813 non-null   str
 56  sought_treatment                   3095 non-null   str
 57  family_history                     3095 non-null   str
 58  interference_when_treated          2168 non-null   str
 59  interference_when_not_treated      1173 non-null   str
 60  observations_less_likely_reveal    2707 non-null   str
 61  share_with_friends_family          1836 non-null   float64
 62  bring_up_physical_interview        1836 non-null   str
 63  bring_up_physical_why              0 non-null      float64
 64  bring_up_mental_interview          1173 non-null   str
 65  bring_up_mental_why                1410 non-null   str
 66  openly_identified                  1834 non-null   str
 67  identified_affected_career         222 non-null    str
 68  identified_affected_how            82 non-null     float64
 69  team_reaction_if_knew              417 non-null    float64
 70  observed_unsupportive_response     1171 non-null   str
 71  unsupportive_response_desc         405 non-null    str
 72  observed_supportive_response       1171 non-null   str
 73  supportive_response_desc           0 non-null      float64
 74  industry_support_rating            1834 non-null   float64
 75  improvement_suggestions            1268 non-null   str
 76  additional_comments                493 non-null    str
 77  willing_to_interview               417 non-null    float64
 78  age                                1834 non-null   float64
 79  gender                             1808 non-null   str
 80  country_live                       1171 non-null   str
 81  state_live                         808 non-null    str
 82  race                               1101 non-null   str
 83  country_work                       1171 non-null   str
 84  state_work                         817 non-null    str
dtypes: float64(26), int64(2), str(57)
memory usage: 2.0 MB

In [7]:
df.describe(include="all").T

                                    count unique                               top  freq         mean       std     min     25%     50%     75%     max
source_file                        3095.0    NaN                               NaN   NaN  2016.485622   2.27782  2014.0  2014.0  2017.0  2018.0  2021.0
survey_year                        3095.0    NaN                               NaN   NaN  2016.485622   2.27782  2014.0  2014.0  2017.0  2018.0  2021.0
self_employed                        1241      2                                No  1095          NaN       NaN     NaN     NaN     NaN     NaN     NaN
no_employees                         2836      6                    More than 1000   776          NaN       NaN     NaN     NaN     NaN     NaN     NaN
tech_company                         2836      6                               Yes  1031          NaN       NaN     NaN     NaN     NaN     NaN     NaN
primary_role_tech                    1577      4                               1.0  1181          NaN       NaN     NaN     NaN     NaN     NaN     NaN
benefits                             2193      5                               Yes   972          NaN       NaN     NaN     NaN     NaN     NaN     NaN
know_options                         2673      3                                No  1259          NaN       NaN     NaN     NaN     NaN     NaN     NaN
formal_discussion                    2836      4                                No  1789          NaN       NaN     NaN     NaN     NaN     NaN     NaN
resources                            2836      4                                No  1318          NaN       NaN     NaN     NaN     NaN     NaN     NaN
anonymity                            2836      4                      I don't know   948          NaN       NaN     NaN     NaN     NaN     NaN     NaN
leave_ease                           2836      8                     Somewhat easy   691          NaN       NaN     NaN     NaN     NaN     NaN     NaN
comfort_physical_mental              2836      6                   Physical health  1070          NaN       NaN     NaN     NaN     NaN     NaN     NaN
comfort_supervisor                   2836      4                               Yes  1097          NaN       NaN     NaN     NaN     NaN     NaN     NaN
discussed_with_employer              2836      7                               0.0   883          NaN       NaN     NaN     NaN     NaN     NaN     NaN
comfort_coworkers                    2836      4                      Some of them   774          NaN       NaN     NaN     NaN     NaN     NaN     NaN
discussed_with_coworkers             1572      4                               0.0   722          NaN       NaN     NaN     NaN     NaN     NaN     NaN
coworker_discussed_with_you          1569      4                               0.0   663          NaN       NaN     NaN     NaN     NaN     NaN     NaN
employer_importance_physical       1577.0    NaN                               NaN   NaN     6.317058  2.279832     0.0     5.0     7.0     8.0    10.0
employer_importance_mental         1577.0    NaN                               NaN   NaN     5.027901  2.500859     0.0     3.0     5.0     7.0    10.0
coverage_mental_health                259      4                               1.0   142          NaN       NaN     NaN     NaN     NaN     NaN     NaN
know_resources                        259      3                       I know some    93          NaN       NaN     NaN     NaN     NaN     NaN     NaN
reveal_to_clients                     259      5              Not applicable to me    79          NaN       NaN     NaN     NaN     NaN     NaN     NaN
reveal_to_coworkers                   259      5              Not applicable to me    84          NaN       NaN     NaN     NaN     NaN     NaN     NaN
productivity_affected                 259      4                               Yes   194          NaN       NaN     NaN     NaN     NaN     NaN     NaN
productivity_percent_affected         194      4                             1-25%    83          NaN       NaN     NaN     NaN     NaN     NaN     NaN
have_prev_employers                1173.0    NaN                               NaN   NaN      0.87809  0.327321     0.0     1.0     1.0     1.0     1.0
prev_tech_company                    1546      4                               1.0   848          NaN       NaN     NaN     NaN     NaN     NaN     NaN
prev_benefits                        1546      4                          Some did   524          NaN       NaN     NaN     NaN     NaN     NaN     NaN
prev_know_options                    1546      5               I was aware of some   491          NaN       NaN     NaN     NaN     NaN     NaN     NaN
prev_formal_discussion               1546      4                          None did  1038          NaN       NaN     NaN     NaN     NaN     NaN     NaN
prev_resources                       1546      3                          None did  1007          NaN       NaN     NaN     NaN     NaN     NaN     NaN
prev_anonymity                       1546      4                      I don't know  1010          NaN       NaN     NaN     NaN     NaN     NaN     NaN
prev_comfort_physical_mental         1546      3                   Physical health  1154          NaN       NaN     NaN     NaN     NaN     NaN     NaN
prev_comfort_supervisor              1546      4   Some of my previous supervisors   740          NaN       NaN     NaN     NaN     NaN     NaN     NaN
prev_discussed_with_employer         1546      4                               0.0   973          NaN       NaN     NaN     NaN     NaN     NaN     NaN
prev_comfort_coworkers               1546      4  At some of my previous employers   761          NaN       NaN     NaN     NaN     NaN     NaN     NaN
prev_discussed_with_coworkers        1538      4                               0.0   810          NaN       NaN     NaN     NaN     NaN     NaN     NaN
prev_employer_importance_physical  1546.0    NaN                               NaN   NaN     5.413325  2.603817     0.0     4.0     5.0     7.0    10.0
prev_employer_importance_mental    1546.0    NaN                               NaN   NaN     3.518111  2.534422     0.0     1.0     3.0     5.0    10.0
currently_disordered                 1173      4                               Yes   515          NaN       NaN     NaN     NaN     NaN     NaN     NaN
diagnosed_disorder                    515      2                               Yes   503          NaN       NaN     NaN     NaN     NaN     NaN     NaN
disorder_anxiety                      0.0    NaN                               NaN   NaN          NaN       NaN     NaN     NaN     NaN     NaN     NaN
disorder_mood                         0.0    NaN                               NaN   NaN          NaN       NaN     NaN     NaN     NaN     NaN     NaN
disorder_psychotic                    0.0    NaN                               NaN   NaN          NaN       NaN     NaN     NaN     NaN     NaN     NaN
disorder_eating                       0.0    NaN                               NaN   NaN          NaN       NaN     NaN     NaN     NaN     NaN     NaN
disorder_adh_add                      0.0    NaN                               NaN   NaN          NaN       NaN     NaN     NaN     NaN     NaN     NaN
disorder_personality                  0.0    NaN                               NaN   NaN          NaN       NaN     NaN     NaN     NaN     NaN     NaN
disorder_ocd                          0.0    NaN                               NaN   NaN          NaN       NaN     NaN     NaN     NaN     NaN     NaN
disorder_ptsd                         0.0    NaN                               NaN   NaN          NaN       NaN     NaN     NaN     NaN     NaN     NaN
disorder_stress_response              0.0    NaN                               NaN   NaN          NaN       NaN     NaN     NaN     NaN     NaN     NaN
disorder_dissociative                 0.0    NaN                               NaN   NaN          NaN       NaN     NaN     NaN     NaN     NaN     NaN
disorder_substance_use                0.0    NaN                               NaN   NaN          NaN       NaN     NaN     NaN     NaN     NaN     NaN
disorder_addictive                    0.0    NaN                               NaN   NaN          NaN       NaN     NaN     NaN     NaN     NaN     NaN
disorder_other                        0.0    NaN                               NaN   NaN          NaN       NaN     NaN     NaN     NaN     NaN     NaN
past_disorder                        1813      4                               Yes   782          NaN       NaN     NaN     NaN     NaN     NaN     NaN
sought_treatment                     3095      6                                 1   865          NaN       NaN     NaN     NaN     NaN     NaN     NaN
family_history                       3095      3                                No  1359          NaN       NaN     NaN     NaN     NaN     NaN     NaN
interference_when_treated            2168      5                         Sometimes   792          NaN       NaN     NaN     NaN     NaN     NaN     NaN
interference_when_not_treated        1173      5                             Often   496          NaN       NaN     NaN     NaN     NaN     NaN     NaN
observations_less_likely_reveal      2707      3                                No  1924          NaN       NaN     NaN     NaN     NaN     NaN     NaN
share_with_friends_family          1836.0    NaN                               NaN   NaN     6.404139  2.747714     0.0     5.0     7.0    8.25    10.0
bring_up_physical_interview          1836      3                             Maybe   755          NaN       NaN     NaN     NaN     NaN     NaN     NaN
bring_up_physical_why                 0.0    NaN                               NaN   NaN          NaN       NaN     NaN     NaN     NaN     NaN     NaN
bring_up_mental_interview            1173      3                                No   821          NaN       NaN     NaN     NaN     NaN     NaN     NaN
bring_up_mental_why                  1410   1385                                \n     6          NaN       NaN     NaN     NaN     NaN     NaN     NaN
openly_identified                    1834      6                               0.0   668          NaN       NaN     NaN     NaN     NaN     NaN     NaN
identified_affected_career            222      4                               0.0   113          NaN       NaN     NaN     NaN     NaN     NaN     NaN
identified_affected_how              82.0    NaN                               NaN   NaN     3.902439  2.502393     0.0     2.0     3.0    5.75    10.0
team_reaction_if_knew               417.0    NaN                               NaN   NaN     5.354916  2.296251     0.0     4.0     5.0     7.0    10.0
observed_unsupportive_response       1171      5                                No   501          NaN       NaN     NaN     NaN     NaN     NaN     NaN
unsupportive_response_desc            405    403                                 .     2          NaN       NaN     NaN     NaN     NaN     NaN     NaN
observed_supportive_response         1171      5                                No   415          NaN       NaN     NaN     NaN     NaN     NaN     NaN
supportive_response_desc              0.0    NaN                               NaN   NaN          NaN       NaN     NaN     NaN     NaN     NaN     NaN
industry_support_rating            1834.0    NaN                               NaN   NaN     2.572519  0.953031     1.0     2.0     3.0     3.0     5.0
improvement_suggestions              1268   1241                                \n     5          NaN       NaN     NaN     NaN     NaN     NaN     NaN
additional_comments                   493    365                                No    36          NaN       NaN     NaN     NaN     NaN     NaN     NaN
willing_to_interview                417.0    NaN                               NaN   NaN     0.366906   0.48254     0.0     0.0     0.0     1.0     1.0
age                                1834.0    NaN                               NaN   NaN    34.811341  9.723979     0.0    28.0    34.0    40.0   223.0
gender                               1808    119                              Male   747          NaN       NaN     NaN     NaN     NaN     NaN     NaN
country_live                         1171     56          United States of America   809          NaN       NaN     NaN     NaN     NaN     NaN     NaN
state_live                            808     43                          Illinois   126          NaN       NaN     NaN     NaN     NaN     NaN     NaN
race                                 1101     10                             White   956          NaN       NaN     NaN     NaN     NaN     NaN     NaN
country_work                         1171     58          United States of America   817          NaN       NaN     NaN     NaN     NaN     NaN     NaN
state_work                            817     44                          Illinois   127          NaN       NaN     NaN     NaN     NaN     NaN     NaN

In [9]:
missing = pd.DataFrame({
    "Missing Values": df.isna().sum(),
    "Missing %": (df.isna().mean()*100).round(2),
    "Unique": df.nunique(dropna=True),
    "Datatype": df.dtypes
})

missing.sort_values("Missing %", ascending=False)

                                   Missing Values  Missing %  Unique Datatype
disorder_ptsd                                3095     100.00       0  float64
disorder_ocd                                 3095     100.00       0  float64
disorder_personality                         3095     100.00       0  float64
disorder_adh_add                             3095     100.00       0  float64
disorder_eating                              3095     100.00       0  float64
disorder_dissociative                        3095     100.00       0  float64
disorder_other                               3095     100.00       0  float64
bring_up_physical_why                        3095     100.00       0  float64
supportive_response_desc                     3095     100.00       0  float64
disorder_addictive                           3095     100.00       0  float64
disorder_mood                                3095     100.00       0  float64
disorder_anxiety                             3095     100.00       0  float64
disorder_psychotic                           3095     100.00       0  float64
disorder_substance_use                       3095     100.00       0  float64
disorder_stress_response                     3095     100.00       0  float64
identified_affected_how                      3013      97.35      10  float64
productivity_percent_affected                2901      93.73       4      str
identified_affected_career                   2873      92.83       4      str
productivity_affected                        2836      91.63       4      str
know_resources                               2836      91.63       3      str
coverage_mental_health                       2836      91.63       4      str
reveal_to_coworkers                          2836      91.63       5      str
reveal_to_clients                            2836      91.63       5      str
unsupportive_response_desc                   2690      86.91     403      str
team_reaction_if_knew                        2678      86.53      11  float64
willing_to_interview                         2678      86.53       2  float64
additional_comments                          2602      84.07     365      str
diagnosed_disorder                           2580      83.36       2      str
state_live                                   2287      73.89      43      str
state_work                                   2278      73.60      44      str
race                                         1994      64.43      10      str
observed_unsupportive_response               1924      62.16       5      str
country_work                                 1924      62.16      58      str
observed_supportive_response                 1924      62.16       5      str
country_live                                 1924      62.16      56      str
interference_when_not_treated                1922      62.10       5      str
bring_up_mental_interview                    1922      62.10       3      str
currently_disordered                         1922      62.10       4      str
have_prev_employers                          1922      62.10       2  float64
self_employed                                1854      59.90       2      str
improvement_suggestions                      1827      59.03    1241      str
bring_up_mental_why                          1685      54.44    1385      str
prev_discussed_with_coworkers                1557      50.31       4      str
prev_resources                               1549      50.05       3      str
prev_employer_importance_physical            1549      50.05      11  float64
prev_employer_importance_mental              1549      50.05      11  float64
prev_formal_discussion                       1549      50.05       4      str
prev_discussed_with_employer                 1549      50.05       4      str
prev_comfort_coworkers                       1549      50.05       4      str
prev_know_options                            1549      50.05       5      str
prev_comfort_supervisor                      1549      50.05       4      str
prev_tech_company                            1549      50.05       4      str
prev_benefits                                1549      50.05       4      str
prev_comfort_physical_mental                 1549      50.05       3      str
prev_anonymity                               1549      50.05       4      str
coworker_discussed_with_you                  1526      49.31       4      str
discussed_with_coworkers                     1523      49.21       4      str
primary_role_tech                            1518      49.05       4      str
employer_importance_physical                 1518      49.05      11  float64
employer_importance_mental                   1518      49.05      11  float64
gender                                       1287      41.58     119      str
past_disorder                                1282      41.42       4      str
age                                          1261      40.74      55  float64
industry_support_rating                      1261      40.74       5  float64
openly_identified                            1261      40.74       6      str
bring_up_physical_interview                  1259      40.68       3      str
share_with_friends_family                    1259      40.68      11  float64
interference_when_treated                     927      29.95       5      str
benefits                                      902      29.14       5      str
know_options                                  422      13.63       3      str
observations_less_likely_reveal               388      12.54       3      str
discussed_with_employer                       259       8.37       7      str
comfort_supervisor                            259       8.37       4      str
tech_company                                  259       8.37       6      str
no_employees                                  259       8.37       6      str
comfort_coworkers                             259       8.37       4      str
formal_discussion                             259       8.37       4      str
resources                                     259       8.37       4      str
anonymity                                     259       8.37       4      str
leave_ease                                    259       8.37       8      str
comfort_physical_mental                       259       8.37       6      str
source_file                                     0       0.00       6    int64
survey_year                                     0       0.00       6    int64
sought_treatment                                0       0.00       6      str
family_history                                  0       0.00       3      str

## Duplicate Records

Duplicate observations provide no additional information and may bias statistical summaries.

Exact duplicate rows are removed while preserving the first occurrence.

In [10]:
print("Duplicates before:", df.duplicated().sum())

df = df.drop_duplicates()

print("Duplicates after :", df.duplicated().sum())

Duplicates before: 13
Duplicates after : 0

## Remove Completely Empty Columns

Columns containing no information (100% missing values) cannot contribute to analysis or modelling.

These columns are removed.

In [11]:
empty_cols = df.columns[df.isna().all()]

print(f"Columns removed: {len(empty_cols)}")

empty_cols.tolist()

Columns removed: 15

['disorder_anxiety',
 'disorder_mood',
 'disorder_psychotic',
 'disorder_eating',
 'disorder_adh_add',
 'disorder_personality',
 'disorder_ocd',
 'disorder_ptsd',
 'disorder_stress_response',
 'disorder_dissociative',
 'disorder_substance_use',
 'disorder_addictive',
 'disorder_other',
 'bring_up_physical_why',
 'supportive_response_desc']

In [12]:
df.drop(columns=empty_cols, inplace=True)

print(df.shape)

(3082, 70)

## Standardize Missing Values

Survey datasets often contain several textual representations of missing information such as:

- NA
- N/A
- None
- Unknown
- Blank strings

These are converted into proper NaN values.

In [14]:
missing_values = [
    "",
    " ",
    "NA",
    "N/A",
    "None",
    "none",
    "NULL",
    "null",
    "nan",
    "NaN",
    "Unknown",
    "unknown"
]

df.replace(missing_values, np.nan, inplace=True)

,source_file,survey_year,self_employed,no_employees,tech_company,primary_role_tech,benefits,know_options,formal_discussion,resources,anonymity,leave_ease,comfort_physical_mental,comfort_supervisor,discussed_with_employer,comfort_coworkers,discussed_with_coworkers,coworker_discussed_with_you,employer_importance_physical,employer_importance_mental,coverage_mental_health,know_resources,reveal_to_clients,reveal_to_coworkers,productivity_affected,productivity_percent_affected,have_prev_employers,prev_tech_company,prev_benefits,prev_know_options,prev_formal_discussion,prev_resources,prev_anonymity,prev_comfort_physical_mental,prev_comfort_supervisor,prev_discussed_with_employer,prev_comfort_coworkers,prev_discussed_with_coworkers,prev_employer_importance_physical,prev_employer_importance_mental,currently_disordered,diagnosed_disorder,past_disorder,sought_treatment,family_history,interference_when_treated,interference_when_not_treated,observations_less_likely_reveal,share_with_friends_family,bring_up_physical_interview,bring_up_mental_interview,bring_up_mental_why,openly_identified,identified_affected_career,identified_affected_how,team_reaction_if_knew,observed_unsupportive_response,unsupportive_response_desc,observed_supportive_response,industry_support_rating,improvement_suggestions,additional_comments,willing_to_interview,age,gender,country_live,state_live,race,country_work,state_work
0,2014,2014,NaN,6-25,Yes,NaN,Yes,Not sure,No,Yes,Yes,Somewhat easy,Yes,Yes,No,Some of them,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,No,Often,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2014,2014,NaN,More than 1000,No,NaN,Don't know,No,Don't know,Don't know,Don't know,Don't know,Don't know,No,Maybe,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,Rarely,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014,2014,NaN,6-25,Yes,NaN,No,No,No,No,Don't know,Somewhat difficult,No,Yes,No,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,Rarely,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2014,2014,NaN,26-100,Yes,NaN,No,Yes,No,No,No,Somewhat difficult,No,No,Yes,Some of them,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,Often,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2014,2014,NaN,100-500,Yes,NaN,Yes,No,Don't know,Don't know,Don't know,Don't know,Don't know,Yes,No,Some of them,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,Never,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3090,2021,2021,NaN,26-100,1.0,1.0,No,No,No,No,I don't know,Somewhat easy,Physical health,Yes,0.0,No,1.0,0.0,4.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,"No, none did",N/A (none offered),None did,None did,I don't know,Physical health,Some of my previous supervisors,1.0,At some of my previous employers,1.0,6.0,2.0,NaN,NaN,Yes,1,I don't know,NaN,NaN,NaN,6.0,Maybe,NaN,"Of course, if we are talking about a physical ...",0,NaN,NaN,NaN,NaN,During pair programming I could notice some co...,NaN,2.0,It seems to me that bad management makes a hug...,"It is normal having people from one country, l...",NaN,33.0,Male,NaN,NaN,NaN,NaN,NaN
3091,2021,2021,NaN,100-500,1.0,1.0,No,NaN,I don't know,No,I don't know,Somewhat easy,Physical health,Maybe,0.0,Maybe,0.0,0.0,8.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,"No, none did",N/A (none offered),None did,None did,I don't know,Physical health,"No, none of my previous supervisors",0.0,"No, at none of my previous employers",0.0,8.0,5.0,NaN,NaN,Possibly,0,Yes,NaN,NaN,No,6.0,Maybe,NaN,If can affect by future work and don't know ho...,0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,49.0,Male,NaN,NaN,NaN,NaN,NaN
3092,2021,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,"No, I don't know any","No, because it would impact me negatively",Not applicable to me,Yes,1-25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Don't Know,0,No,NaN,NaN,NaN,0.0,No,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,28.0,NaN,NaN,NaN,NaN,NaN,NaN
3093,2021,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,I know some,"No, because it doesn't matter","No, because it doesn't matter",Yes,51-75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Don't Know,0,No,NaN,NaN,Yes,3.0,No,NaN,It will impact on the job,0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,"Support them , and provide less stress time fo...",No thank you,NaN,26.0,Male,NaN,NaN,NaN,NaN,NaN
3094,2021,2021,NaN,26-100,1.0,1.0,I don't know,No,No,No,No,Somewhat difficult,Physical health,Maybe,1.0,Maybe,1.0,1.0,8.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,"No, none did","No, I only became aware later",None did,None did,No,Physical health,"No, none of my previous supervisors",0.0,"No, at none of my previous employers",0.0,0.0,0.0,NaN,NaN,NaN,1,No,NaN,NaN,Maybe,6.0,Yes,NaN,Luckily we have social security civered under ...,0,NaN,NaN,NaN,NaN,They put more pressure to them and ultimately ...,NaN,3.0,NaN,NaN,NaN,38.0,male,NaN,NaN,NaN,NaN,NaN

## Clean Text Columns

Text responses are standardized to improve consistency across survey years.

Cleaning includes:

- removing leading/trailing spaces
- converting repeated spaces to a single space
- preserving the original capitalization where meaningful

In [15]:
text_cols = df.select_dtypes(include="object").columns

for col in text_cols:
    df[col] = (
        df[col]
        .astype("string")
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
    )

## Validate Data Types

Numeric variables should be stored using numeric data types whenever possible.

Object columns that contain numeric information are converted safely.

In [17]:
numeric_candidates = [
    "age",
    "survey_year"
]

for col in numeric_candidates:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

## Remove Impossible Ages

Survey respondents with unrealistic ages likely represent data entry errors.

Valid ages are restricted to:

18–100 years

In [18]:
if "age" in df.columns:

    print(df["age"].describe())

    df.loc[(df["age"] < 18) | (df["age"] > 100), "age"] = np.nan

count    1834.000000
mean       34.811341
std         9.723979
min         0.000000
25%        28.000000
50%        34.000000
75%        40.000000
max       223.000000
Name: age, dtype: float64

## Final Validation

After cleaning, several validation checks are performed to ensure dataset quality.

In [19]:
print("="*50)

print("Rows:", df.shape[0])

print("Columns:", df.shape[1])

print("Duplicate rows:", df.duplicated().sum())

print("\nRemaining Missing Values")

display(
    df.isna()
      .sum()
      .sort_values(ascending=False)
      .head(25)
)

print("\nData Types")

display(df.dtypes.value_counts())

print("="*50)

==================================================
Rows: 3082
Columns: 70
Duplicate rows: 0

Remaining Missing Values

identified_affected_how           3000
productivity_percent_affected     2888
identified_affected_career        2860
know_resources                    2823
reveal_to_coworkers               2823
productivity_affected             2823
reveal_to_clients                 2823
coverage_mental_health            2823
unsupportive_response_desc        2678
team_reaction_if_knew             2665
willing_to_interview              2665
additional_comments               2600
diagnosed_disorder                2567
state_live                        2274
state_work                        2265
race                              1981
country_live                      1911
country_work                      1911
observed_supportive_response      1911
observed_unsupportive_response    1911
currently_disordered              1909
interference_when_not_treated     1909
have_prev_employers               1909
bring_up_mental_interview         1909
self_employed                     1854
dtype: int64

Data Types

string     57
float64    11
int64       2
Name: count, dtype: int64

==================================================

In [204]:
clean_df.to_csv(
    "../data/processed/cleaned_osmi_data.csv",
    index=False
)

print("✅ Clean dataset exported successfully.")

✅ Clean dataset exported successfully.

In [20]:
df.to_csv("../data/processed/cleaned_osmi_data.csv", index=False)

print("Dataset saved successfully.")

Dataset saved successfully.